import os
env = Environment(ENV = os.environ)
env.Java(target='.', source='.')
env.JavaH('.', 'org/aegisknight/audiere/AudioDevice.class')
env.JavaH('.', 'org/aegisknight/audiere/OutputStream.class')
