import os

XPCOM_BASE = 'C:/gecko-sdk/xpcom'
XPIDL = os.path.join(XPCOM_BASE, 'bin', 'xpidl')

TypeLib = Builder(action = '${XPIDL} -m typelib $XPIDLFLAGS $SOURCE')
Header  = Builder(action = '${XPIDL} -m header $XPIDLFLAGS $SOURCE')

env = Environment(
    ENV = os.environ,
    BUILDERS = { 'TypeLib' : TypeLib, 'Header' : Header },
    XPIDL = XPIDL,
    XPIDLFLAGS = '-I%s' % os.path.join(XPCOM_BASE, 'idl'))

INTERFACES = [
    'adrIAudiereService',
    'adrIAudioDevice',
    'adrIOutputStream']

for i in INTERFACES:
    env.TypeLib(i + '.xpt', i + '.idl')
    env.Header(i + '.h', i + '.idl')
