#include "nsISupports.idl"


[scriptable, uuid(ea567a5a-1dd1-11b2-97ea-d562ef6cf40a)]
interface mozIAudioStream : nsISupports
{
  const long VOLUME_MIN = 0;
  const long VOLUME_MAX = 255;
  const long PAN_LEFT   = -255;
  const long PAN_CENTER = 0;
  const long PAN_RIGHT  = 255;

  
  void play();
  void pause();
  void reset();

  attribute boolean repeating;
  attribute short   volume;
  attribute short   pan;

  readonly attribute boolean playing;
};
