import os

Import('base_env PREFIX')

sources = Split("""
    debug
    device
    device_al
    device_mixer
    device_null
    file_ansi
    input
    input_ogg
    input_wav
    noise
    repeatable
    resampler
    sample_buffer
    square_wave
    sound
    threads_posix
    timer_posix
    tone
    utility
    version
""")

sources = map(lambda n: n + '.cpp', sources)

env = base_env.Copy()
target = env.SharedLibrary('audiere', sources)

env.Install(os.path.join(PREFIX, 'include'), 'audiere.h')
env.Install(os.path.join(PREFIX, 'lib32'), target)
