import os

Import('base_env PREFIX')

env = base_env.Copy()

wxconfig = env.WhereIs('wx-config')
if wxconfig:
    env.ParseConfig(wxconfig + ' --cxxflags --libs')

    env.Prepend(CPPPATH=['#/src'],
                LIBPATH=['#/src'],
                LIBS=['audiere'])

    wxPlayer = env.Program('wxPlayer', [
        'DeviceFrame.cpp',
        'EditLoopPointsDialog.cpp',
        'NewDeviceDialog.cpp',
        'SoundEffectFrame.cpp',
        'StreamFrame.cpp',
        'TagsDialog.cpp',
        'wxPlayer.cpp'])

    env.Install(os.path.join(PREFIX, 'bin'), wxPlayer)
