.\"
.\" mad - MPEG audio decoder
.\" Copyright (C) 2000-2001 Robert Leslie
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
.\"
.\" $Id$
.\"
.TH MADPLAY 1 "03 April 2001" "MAD" "MPEG Audio Decoder"
.SH NAME
madplay \- decode and play MPEG audio stream(s)
.SH SYNOPSIS
.B madplay
.RI [ options ]
.I file
\&...
.br
.B madplay
.RI [ options ]
.B \-o
.RI [ type :] path
.I file
\&...
.SH DESCRIPTION
.B madplay
is a command-line front-end to the MAD library.
.PP
MAD is a high-quality MPEG audio decoder. It currently supports MPEG-1 and the
MPEG-2 extension to Lower Sampling Frequencies, as well as the so-called
MPEG\ 2.5 format. All three audio layers (Layer\ I, Layer\ II, and Layer\ III
a.k.a. MP3) are fully implemented.
.PP
Among the special features of MAD are 24-bit PCM resolution and 100%
fixed-point (integer) computation.
.PP
MAD does not yet support MPEG-2 multichannel audio (although it should be
backward compatible with such streams) nor does it currently support AAC.
.PP
By default
.B
madplay
reads and decodes one or more input
.IR file s
containing MPEG audio data and plays them on the native audio device. If the
input file is a single dash (\-), data is read from standard input.
.PP
Decoded output may optionally be redirected to a file instead of being played
on the audio device by using the
.B \-o
.RB ( \-\-output )
option.
.SH OPTIONS
.SS Verbosity
.TP
.BR \-v " or " \-\-verbose
Show information about the stream during decoding, including playing time,
audio layer, bit rate, sampling frequency, and stereo mode.
.TP
.BR \-q " or " \-\-quiet
Do not show any information during decoding, except warnings.
.TP
.BR \-Q " or " \-\-very\-quiet
Do not show any information during decoding, including warnings.
.SS "Audio Output"
.TP
\fB\-o\fR or \fB\-\-output=\fR[\fItype\fR:]\fIpath\fR
Direct output to
.IR path ,
rather than playing audio on the native audio device. The format of the output
is specified by
.I type
which can be any of the supported output formats (see below.) If a format is
not specified, one will be inferred from
.IR path .
If
.I path
is a single dash (\-), the output will be written to standard output.
.TP
.BR \-d " or " \-\-no\-dither
Do not dither the output PCM samples. This may result in lower sound quality
but is useful for analyzing output from the decoder.
.TP
.B \-\-downsample
Reduce the output sampling frequency 2:1. This also reduces the computational
overhead of the decoder.
.TP
\fB\-\-fade\-in\fR[\fB=\fIduration\fR]
Gradually fade-in the audio from each file over
.IR duration .
If not specified, the default duration is
.B 0:05
(five seconds.)
.TP
\fB\-a\fR or \fB\-\-attenuate=\fIdecibels\fR or \fB\-\-amplify=\fIdecibels\fR
Attenuate or amplify the signal by
.I decibels
(dB).
The signal is attenuated if the decibel value is negative; it is amplified if
the value is positive.
The decibel value must be in the range \-175 to +18.
The value may be fractional, e.g. \-1.5.
A value of 0 will leave the signal unchanged.
Each step of 6\ dB will approximately halve (in the negative direction) or
double (in the positive direction) the strength of the signal.
.SS "Channel Selection"
.PP
For dual channel streams, an output channel should be selected. If one is not
selected, the first (left) channel will be used.
.PP
For stereo streams, making a channel selection other than stereo will cause
the output to be monaural.
.TP
.BR \-1 " or " \-\-left
Output the first (left) channel only.
.TP
.BR \-2 " or " \-\-right
Output the second (right) channel only.
.TP
.BR \-m " or " \-\-mono
Mix the left and right channels together.
.TP
.BR \-S " or " \-\-stereo
Force stereo output, even if the stream is single or dual channel.
.SS "Playback"
.TP
\fB\-s\fR or \fB\-\-start=\fItime\fR
Begin playing at
.IR time ,
given as an offset from the beginning of the first file
.RB ( 0:00:00 ),
seeking as necessary.
.TP
\fB\-t\fR or \fB\-\-time=\fIduration\fR
Stop playback after the playing time of the output audio equals
.IR duration .
.TP
.BR \-z " or " \-\-shuffle
Randomize the list of files given on the command line for playback.
.TP
\fB\-r\fR or \fB\-\-repeat\fR[\fB=\fImax\fR]
Play the input files
.I max
times, or indefinitely. Playback can still be stopped by giving a time limit
with the
.B \-t
.RB ( \-\-time )
option. If
.B \-z
.RB ( \-\-shuffle )
is also used, the files will be continuously shuffled and repeated in such a
way that the same file is not played again until at least half of the other
files have played in the interim.
.SS "Miscellaneous"
.TP
.BR \-V " or " \-\-version
Display the effective version and build options for
.BR madplay ,
and exit.
.TP
.B \-\-license
Display a license message and exit.
.TP
.BR \-h " or " \-\-help
Display a usage message and exit.
.SH "Output Formats"
Other than playing on the native audio device, the following output formats
are supported:
.TP
.B raw
binary signed 16-bit host-endian linear PCM, stereo interleaved
.TP
.B wave
Microsoft RIFF/WAVE, 16-bit PCM format
.RB ( *.wav )
.TP
.B snd
Sun/NeXT audio file format, 8-bit ISDN mu-law
.RB ( *.au ,
.BR *.snd )
.TP
.B hex
hexadecimal signed 24-bit linear PCM, stereo interleaved, one sample per
output line (debug builds only)
.TP
.B null
no output (usually for testing or timing the decoder)
.SH "Time Specifications"
For options which accept a time or duration argument, the following time
specifications are recognized:
.TP
.IB hh : mm : ss . ddd
Hours, minutes, seconds, and decimal fractions of a second. This specification
is flexible;
.IB hh : mm : ss\c
,
.IB mmm : ss\c
,
.BI : ss\c
,
.IB sss . ddd\c
,
.BI . ddd\c
, and
.I ssss
are all acceptable. The component values are not constrained to any particular
range or number of digits.
.TP
.IB frac / unit
A length of time specified as a rational number, in seconds. This can be used
for sample-granularity, for example
.B 32/44100
for 32 samples, assuming a 44100 Hz sample frequency.
.TP
.IB time1 + time2
A composite time made by adding two time values together. This permits mixing
the above specification forms.
.PP
The resolution of any time value cannot exceed 1/352800000 seconds.
.SH DIAGNOSTICS
.TP
.B "error: frame #: lost synchronization"
If encountered at the beginning of a file, this means the file contains
something other than an ID3v2 tag before the MPEG audio data. If encountered
in the middle of a file, it may mean the file is corrupt. This message is most
commonly encountered, however, at the end of a file if the file contains an
ID3v1 tag that is not aligned to an MPEG audio frame boundary. In this case,
the message is harmless and may be ignored.
.PP
.TP
.B "error: frame #: bad main_data_begin pointer"
This message can occur while decoding a Layer\ III stream that has been cut or
spliced without preserving its bit reservoir. The affected frame cannot be
properly decoded, but it will be used to help restore the bit reservoir for
the next frame.
.PP
Most other messages indicate a deficiency in the input stream.
.PP
When a frame cannot be properly decoded, a concealment strategy is used as
follows:
.TP 2
\(bu
If the previous frame was properly decoded, it is repeated in place of the
current frame.
.TP 2
\(bu
If the previous frame was
.I not
properly decoded, the current frame is muted.
.SH "CONFORMING TO"
MAD conforms to Part\ 3 of the ISO/IEC\ 11172 (MPEG-1) international standard
for decoding MPEG audio. In addition, MAD supports the extension to Lower
Sampling Frequencies (LSF) as defined in Part\ 3 of ISO/IEC\ 13818 (MPEG-2).
.PP
The output from MAD has been tested and found to satisfy the ISO/IEC\ 11172-4
computational accuracy requirements for compliance. In most configurations,
MAD is a
.I "Full Layer\ III ISO/IEC\ 11172-3 audio decoder"
as defined by the standard.
.SH NOTES
Because MAD produces output samples with a precision greater than 24 bits, by
default
.B madplay
will dither the output to the necessary number of bits, usually 16. This
produces high quality audio that generally sounds superior to the output of a
simple rounding algorithm. However, dithering may unfavorably affect an
analytic examination of the output, and therefore it may be disabled by using
the
.B \-d
.RB ( \-\-no\-dither )
option.
.PP
MAD is implemented entirely without the use of floating point arithmetic and
should therefore perform well on all architectures, especially those without
an FPU.
.SH BUGS
Granularity of start and stop times
.RB ( \-\-start
and
.BR \-\-time )
is not yet as fine as this specification suggests.
.SH AUTHOR
Robert Leslie <rob@mars.org>
.SH "SEE ALSO"
ISO/IEC\ 11172-3, ISO/IEC\ 13818-3; tests for compliance are defined in
ISO/IEC\ 11172-4 and ISO/IEC\ 13818-4.
